import { useStore, fmtR } from '../lib/store'

export function Analises({ tipo }: { tipo: 'abc' | 'qpr' | 'alertas' | 'caixa' | 'historico' | 'backup' }) {
  const { produtos, vendas, clientes, caixaEntradas, caixas, caixaAberto, abrirCaixa, fecharCaixa, resetDemo, clearAll } = useStore()
  const saidas = vendas.flatMap(v => v.itens.map(i => ({ ...i, data: v.data })))

  if (tipo === 'alertas') {
    const criticos = produtos.filter(p => p.estoque <= p.estoqueMin)
    const alertas = produtos.filter(p => p.estoque > p.estoqueMin && p.estoque <= p.pontoPedido)
    const credito = clientes.filter(c => c.saldo > c.limite)
    return <div className="flex flex-col gap-4"><h2 className="text-xl font-bold">Alertas</h2>{[...criticos.map(p => ['Crítico', `${p.nome}: ${p.estoque} unidades em estoque`, 'badge-danger']), ...alertas.map(p => ['Reposição', `${p.nome} atingiu o ponto de pedido (${p.estoque} un)`, 'badge-warning']), ...credito.map(c => ['Crédito', `${c.nome} excedeu o limite de crédito`, 'badge-danger'])].length ? <div className="flex flex-col gap-2">{[...criticos.map(p => ['Crítico', `${p.nome}: ${p.estoque} unidades em estoque`, 'badge-danger']), ...alertas.map(p => ['Reposição', `${p.nome} atingiu o ponto de pedido (${p.estoque} un)`, 'badge-warning']), ...credito.map(c => ['Crédito', `${c.nome} excedeu o limite de crédito`, 'badge-danger'])].map((a, i) => <div key={i} className="card-adega p-4 flex gap-3 items-center"><span className={`badge-adega ${a[2]}`}>{a[0]}</span><span className="text-sm">{a[1]}</span></div>)}</div> : <div className="card-adega p-8 text-center text-success">Tudo em ordem.</div>}</div>
  }

  if (tipo === 'historico') return <div className="flex flex-col gap-4"><h2 className="text-xl font-bold">Histórico de Vendas</h2><div className="card-adega overflow-hidden"><div className="overflow-x-auto"><table className="tbl-adega"><thead><tr><th>Data</th><th>Cliente</th><th>Produtos</th><th>Total</th><th>Pagamento</th></tr></thead><tbody>{vendas.length ? [...vendas].reverse().map(v => <tr key={v.id}><td>{new Date(v.data + 'T12:00:00').toLocaleDateString('pt-BR')}</td><td>{clientes.find(c => c.id === v.clienteId)?.nome || '—'}</td><td>{v.itens.map(i => `${produtos.find(p => p.id === i.produtoId)?.nome || 'Removido'} x${i.quantidade}`).join(', ')}</td><td className="font-semibold">{fmtR(v.total)}</td><td><span className="badge-adega badge-info">{v.pagamento}</span></td></tr>) : <tr><td colSpan={5} className="text-center py-8 text-muted-foreground">Nenhuma venda registrada</td></tr>}</tbody></table></div></div></div>

  if (tipo === 'caixa') {
    const inicio = caixaAberto?.abertoEm.slice(0, 10) || ''
    const entradasFiltradas = caixaEntradas.filter(e => e.pagamento !== 'fiado' && (caixaAberto ? e.caixaId === caixaAberto.id || (!e.caixaId && e.data >= inicio) : false))
    const entradas = entradasFiltradas.reduce((s, e) => s + (e.tipo === 'sangria' ? -e.valor : e.valor), 0)
    const vendasTotal = entradasFiltradas.filter(e => e.tipo === 'venda').reduce((s, e) => s + e.valor, 0)
    return <div className="flex flex-col gap-4"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">Caixa</h2>{caixaAberto ? <button onClick={() => { if (confirm('Fechar caixa?')) fecharCaixa() }} className="px-4 py-2 bg-destructive text-destructive-foreground rounded-lg text-sm font-semibold">Fechar caixa</button> : <button onClick={abrirCaixa} className="px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-semibold">Abrir caixa</button>}</div><div className="card-adega p-4"><div className="kpi-label">Status</div><div className={`kpi-value ${caixaAberto ? 'text-success' : 'text-destructive'}`}>{caixaAberto ? `Aberto desde ${new Date(caixaAberto.abertoEm).toLocaleString('pt-BR')}` : 'Caixa fechado'}</div></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{[['Vendas', fmtR(vendasTotal), 'text-success'], ['Saldo em caixa', fmtR(entradas), 'text-primary'], ['Movimentações', entradasFiltradas.length, 'text-warning']].map(x => <div key={x[0] as string} className="card-adega p-4"><div className="kpi-label">{x[0]}</div><div className={`kpi-value ${x[2]}`}>{x[1]}</div></div>)}</div><div className="card-adega overflow-hidden"><table className="tbl-adega"><thead><tr><th>Data fechamento</th><th>Faturamento bruto</th><th>Lucro líquido</th><th>Vendas</th></tr></thead><tbody>{caixas.length ? caixas.map(c => <tr key={c.id}><td>{c.fechadoEm ? new Date(c.fechadoEm).toLocaleString('pt-BR') : '—'}</td><td>{fmtR(c.faturamentoBruto || 0)}</td><td className={(c.lucroLiquido || 0) >= 0 ? 'text-success' : 'text-destructive'}>{fmtR(c.lucroLiquido || 0)}</td><td>{c.vendas || 0}</td></tr>) : <tr><td colSpan={4} className="text-center py-8 text-muted-foreground">Nenhum caixa fechado</td></tr>}</tbody></table></div></div>
  }

  if (tipo === 'backup') return <div className="flex flex-col gap-4"><h2 className="text-xl font-bold">Backup</h2><div className="grid md:grid-cols-2 gap-4"><div className="card-adega p-5"><h3 className="font-bold mb-2">Exportar dados</h3><p className="text-sm text-muted-foreground mb-4">Gere um arquivo JSON com os dados locais.</p><button onClick={() => { const blob = new Blob([JSON.stringify({ produtos, vendas, clientes, caixaEntradas }, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'backup-adega.json'; a.click() }} className="px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm">Baixar backup</button></div><div className="card-adega p-5"><h3 className="font-bold mb-2">Dados de demonstração</h3><p className="text-sm text-muted-foreground mb-4">Restaura os produtos usados na apresentação.</p><button onClick={() => { if (confirm('Restaurar dados de demonstração?')) resetDemo() }} className="px-4 py-2 bg-warning text-white rounded-lg text-sm">Restaurar demo</button></div><div className="card-adega p-5"><h3 className="font-bold mb-2 text-destructive">Zerar sistema</h3><p className="text-sm text-muted-foreground mb-4">Remove todos os dados locais permanentemente.</p><button onClick={() => { if (confirm('Apagar todos os dados?')) clearAll() }} className="px-4 py-2 bg-destructive text-destructive-foreground rounded-lg text-sm">Apagar dados</button></div></div></div>

  const ranking = produtos.map(p => { const qtd = saidas.filter(s => s.produtoId === p.id).reduce((s,i) => s + i.quantidade, 0); return { ...p, qtd, receita: qtd * p.precoVenda } }).sort((a,b) => b.receita-a.receita)
  if (tipo === 'abc') { const total = ranking.reduce((s,p)=>s+p.receita,0); let ac=0; return <div className="flex flex-col gap-4"><h2 className="text-xl font-bold">Curva ABC</h2><div className="card-adega overflow-hidden"><div className="overflow-x-auto"><table className="tbl-adega"><thead><tr><th>#</th><th>Produto</th><th>Classe</th><th>Receita</th><th>%</th><th>% Acum.</th></tr></thead><tbody>{ranking.map((p,i)=>{const pct=total?p.receita/total*100:0; ac+=pct;const cls=ac<=80?'A':ac<=95?'B':'C';return <tr key={p.id}><td>{i+1}</td><td>{p.nome}</td><td><span className={`badge-adega ${cls==='A'?'badge-danger':cls==='B'?'badge-warning':'badge-success'}`}>{cls}</span></td><td>{fmtR(p.receita)}</td><td>{pct.toFixed(1)}%</td><td>{ac.toFixed(1)}%</td></tr>})}</tbody></table></div></div></div> }

  return <div className="flex flex-col gap-4"><h2 className="text-xl font-bold">Matriz QPR</h2><div className="card-adega overflow-hidden"><div className="overflow-x-auto"><table className="tbl-adega"><thead><tr><th>Produto</th><th>Qualidade</th><th>Margem</th><th>Giro</th><th>Classificação</th></tr></thead><tbody>{ranking.map(p=>{const margem=p.precoVenda?((p.precoVenda-p.precoCompra)/p.precoVenda)*100:0;const cls=p.qualidade>=4&&margem>=30&&p.qtd>0?'Estrela':p.qtd>0?'Commodity':'Dor de Cabeça';return <tr key={p.id}><td>{p.nome}</td><td>{p.qualidade}/5</td><td>{margem.toFixed(1)}%</td><td>{p.qtd} un</td><td><span className="badge-adega badge-info">{cls}</span></td></tr>})}</tbody></table></div></div></div>
}
