begin;

-- Hardening incremental e não destrutivo para instalações existentes.
-- Mantém a Data API fechada para visitantes e declara os privilégios usados
-- pelo cliente autenticado de forma explícita.
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
grant usage on schema public to authenticated;

-- Privilégios explícitos: não dependem mais do default legado do Supabase.
-- As policies continuam decidindo quais linhas e papéis podem operar.
grant select, insert, update, delete on
  public.produtos, public.movimentacoes, public.clientes, public.vendas,
  public.itens_venda, public.caixas, public.pedidos_compra,
  public.itens_pedido_compra
to authenticated;
grant select, insert on public.caixa_entradas to authenticated;
grant select, insert, update on public.entregas, public.rastreio_entregadores to authenticated;
grant select, insert on public.rastreio_pontos, public.historico_precos_compra to authenticated;
grant select, insert, update on public.inventarios, public.itens_inventario to authenticated;
grant select on public.assinaturas_lojas, public.auditoria_operacional to authenticated;

do $$
declare sequencia text;
begin
  foreach sequencia in array array[
    'itens_venda_id_seq', 'caixa_entradas_id_seq',
    'itens_pedido_compra_id_seq', 'rastreio_pontos_id_seq',
    'historico_precos_compra_id_seq', 'auditoria_operacional_id_seq'
  ] loop
    if to_regclass('public.' || sequencia) is not null then
      execute format('grant usage, select on sequence public.%I to authenticated', sequencia);
    end if;
  end loop;
end
$$;

-- Telemetria operacional sem payloads pessoais/sigilosos. O navegador apenas
-- insere eventos da própria loja; somente owner/gerente podem consultá-los.
create table if not exists public.erros_aplicacao (
  id bigint generated by default as identity primary key,
  loja_id text not null,
  usuario_id uuid references auth.users(id) on delete set null,
  fingerprint text not null,
  origem text not null check (char_length(origem) between 1 and 120),
  mensagem text not null check (char_length(mensagem) between 1 and 1000),
  contexto jsonb not null default '{}'::jsonb,
  versao text not null default '2.0.0',
  criado_em timestamptz not null default now()
);
create index if not exists erros_aplicacao_loja_criado_idx
  on public.erros_aplicacao (loja_id, criado_em desc);
create index if not exists erros_aplicacao_fingerprint_idx
  on public.erros_aplicacao (loja_id, fingerprint, criado_em desc);

alter table public.erros_aplicacao enable row level security;
revoke all on public.erros_aplicacao from public, anon, authenticated;
grant insert, select on public.erros_aplicacao to authenticated;
grant usage, select on sequence public.erros_aplicacao_id_seq to authenticated;

drop policy if exists "registrar erro da propria loja" on public.erros_aplicacao;
create policy "registrar erro da propria loja"
on public.erros_aplicacao for insert to authenticated
with check (
  usuario_id = (select auth.uid())
  and loja_id = (select private.loja_atual())
);

drop policy if exists "gestao consulta erros da loja" on public.erros_aplicacao;
create policy "gestao consulta erros da loja"
on public.erros_aplicacao for select to authenticated
using (
  loja_id = (select private.loja_atual())
  and (select private.papel_atual()) in ('owner', 'gerente')
);

-- Garante que módulos criados depois do controle de assinatura também sejam
-- bloqueados quando a loja estiver suspensa. Credenciais e telemetria ficam de
-- fora: credenciais são service_role-only e erros precisam continuar chegando.
do $$
declare tabela record;
begin
  for tabela in
    select c.table_name
    from information_schema.columns c
    join information_schema.tables t
      on t.table_schema = c.table_schema and t.table_name = c.table_name
    where c.table_schema = 'public'
      and c.column_name = 'loja_id'
      and t.table_type = 'BASE TABLE'
      and c.table_name not in (
        'perfis', 'assinaturas_lojas', 'whatsapp_credenciais', 'erros_aplicacao'
      )
  loop
    execute format('alter table public.%I enable row level security', tabela.table_name);
    execute format('drop policy if exists "assinatura ativa da loja" on public.%I', tabela.table_name);
    execute format(
      'create policy "assinatura ativa da loja" on public.%I as restrictive for all to authenticated
       using (loja_id = (select private.loja_atual()) and (select private.assinatura_atual_ativa()))
       with check (loja_id = (select private.loja_atual()) and (select private.assinatura_atual_ativa()))',
      tabela.table_name
    );
  end loop;
end
$$;

-- Índices para as consultas mais frequentes, paginação e chaves estrangeiras.
create index if not exists perfis_loja_role_idx on public.perfis (loja_id, role);
create index if not exists produtos_loja_nome_idx on public.produtos (loja_id, nome, id);
create index if not exists movimentacoes_loja_data_id_idx on public.movimentacoes (loja_id, data desc, id);
create index if not exists movimentacoes_produto_idx on public.movimentacoes (produto_id);
create index if not exists clientes_loja_nome_idx on public.clientes (loja_id, nome, id);
create index if not exists vendas_loja_criado_id_idx on public.vendas (loja_id, criado_em desc, id);
create index if not exists itens_venda_venda_idx on public.itens_venda (venda_id);
create index if not exists itens_venda_produto_idx on public.itens_venda (produto_id);
create index if not exists caixas_loja_aberto_idx on public.caixas (loja_id, aberto_em desc, id);
create index if not exists caixa_entradas_loja_data_idx on public.caixa_entradas (loja_id, data desc, id);
create index if not exists caixa_entradas_caixa_idx on public.caixa_entradas (caixa_id);
create index if not exists entregas_loja_status_criado_idx on public.entregas (loja_id, status, criado_em desc, id);
create index if not exists pedidos_compra_loja_status_data_idx on public.pedidos_compra (loja_id, status, data_pedido desc, id);
create index if not exists itens_pedido_compra_pedido_idx on public.itens_pedido_compra (pedido_id);
create index if not exists itens_pedido_compra_produto_idx on public.itens_pedido_compra (produto_id);

-- Ao criar o primeiro owner de uma loja, a assinatura de avaliação passa a ser
-- provisionada automaticamente. Outros colaboradores reutilizam a mesma linha.
create or replace function private.provisionar_assinatura_nova_loja()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.role = 'owner' and new.loja_id is not null and btrim(new.loja_id) <> '' then
    insert into public.assinaturas_lojas (
      loja_id, nome_loja, plano, status, periodo_teste_ate
    ) values (
      new.loja_id, new.loja_id, 'teste', 'trial', now() + interval '7 days'
    ) on conflict (loja_id) do nothing;
  end if;
  return new;
end;
$$;
revoke all on function private.provisionar_assinatura_nova_loja() from public, anon, authenticated;

drop trigger if exists perfis_provisionar_assinatura on public.perfis;
create trigger perfis_provisionar_assinatura
after insert or update of loja_id, role on public.perfis
for each row execute function private.provisionar_assinatura_nova_loja();

-- Recebimento de compra transacional e idempotente. Pedido, estoque,
-- movimentação, histórico de custo e auditoria são confirmados juntos.
create or replace function public.receber_pedido_compra_atomico(p_pedido_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario uuid := auth.uid();
  v_loja text;
  v_papel text;
  v_status text;
  v_recebido_em timestamptz;
  v_item record;
begin
  if v_usuario is null then
    raise exception 'Sessão inválida';
  end if;

  select loja_id, role into v_loja, v_papel
  from public.perfis
  where id = v_usuario and status = 'ativo';

  if v_loja is null or v_papel not in ('owner', 'gerente') then
    raise exception 'Usuário sem permissão para receber compras';
  end if;
  if not (select private.assinatura_atual_ativa()) then
    raise exception 'Assinatura da loja indisponível';
  end if;

  select status, recebido_em into v_status, v_recebido_em
  from public.pedidos_compra
  where id = p_pedido_id and loja_id = v_loja
  for update;

  if not found then
    raise exception 'Pedido de compra não encontrado';
  end if;
  if v_status = 'received' then
    return jsonb_build_object('ok', true, 'duplicado', true, 'pedido_id', p_pedido_id);
  end if;
  if v_status not in ('pending', 'in_transit') then
    raise exception 'Somente pedidos aprovados ou em trânsito podem ser recebidos';
  end if;
  if not exists (
    select 1 from public.itens_pedido_compra
    where pedido_id = p_pedido_id and loja_id = v_loja
  ) then
    raise exception 'Pedido sem itens';
  end if;

  -- Ordem estável de bloqueio reduz a possibilidade de deadlock quando dois
  -- recebimentos incluem o mesmo produto.
  perform produto.id
  from public.produtos produto
  join public.itens_pedido_compra item
    on item.produto_id = produto.id and item.loja_id = produto.loja_id
  where item.pedido_id = p_pedido_id and produto.loja_id = v_loja
  order by produto.id
  for update of produto;

  if exists (
    select 1
    from public.itens_pedido_compra item
    left join public.produtos produto
      on produto.id = item.produto_id and produto.loja_id = item.loja_id
    where item.pedido_id = p_pedido_id
      and item.loja_id = v_loja
      and produto.id is null
  ) then
    raise exception 'Pedido contém produto inexistente';
  end if;

  for v_item in
    select item.produto_id, item.quantidade_solicitada, item.preco_unit_custo,
           produto.fornecedor
    from public.itens_pedido_compra item
    join public.produtos produto
      on produto.id = item.produto_id and produto.loja_id = item.loja_id
    where item.pedido_id = p_pedido_id and item.loja_id = v_loja
    order by item.produto_id
  loop
    update public.produtos
    set estoque = estoque + v_item.quantidade_solicitada,
        preco_compra = case
          when v_item.preco_unit_custo > 0 then v_item.preco_unit_custo
          else preco_compra
        end,
        updated_at = now()
    where id = v_item.produto_id and loja_id = v_loja;

    insert into public.movimentacoes (
      id, user_id, loja_id, produto_id, tipo, quantidade, data, motivo,
      aprovado_por, aprovado_em, obs
    ) values (
      'compra_' || p_pedido_id::text || '_' || v_item.produto_id,
      v_usuario, v_loja, v_item.produto_id, 'entrada',
      v_item.quantidade_solicitada, current_date, 'compra',
      v_usuario, now(), 'Recebimento do pedido ' || p_pedido_id::text
    ) on conflict (id) do nothing;

    if v_item.preco_unit_custo > 0 then
      insert into public.historico_precos_compra (
        loja_id, produto_id, pedido_id, fornecedor, preco_unitario
      ) values (
        v_loja, v_item.produto_id, p_pedido_id, v_item.fornecedor,
        v_item.preco_unit_custo
      );
    end if;
  end loop;

  update public.pedidos_compra
  set status = 'received', recebido_em = now()
  where id = p_pedido_id and loja_id = v_loja;

  insert into public.auditoria_operacional (
    loja_id, usuario_id, acao, entidade, entidade_id, payload
  ) values (
    v_loja, v_usuario, 'recebeu', 'pedido_compra', p_pedido_id::text,
    jsonb_build_object('status_anterior', v_status)
  );

  return jsonb_build_object('ok', true, 'duplicado', false, 'pedido_id', p_pedido_id);
end;
$$;
revoke all on function public.receber_pedido_compra_atomico(uuid) from public, anon;
grant execute on function public.receber_pedido_compra_atomico(uuid) to authenticated;

-- Ponto eletrônico: o PIN deixa de trafegar para o navegador e passa a ser
-- validado por hash dentro do banco.
create extension if not exists pgcrypto with schema extensions;
alter table public.perfis add column if not exists pin_hash text;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'perfis' and column_name = 'pin'
  ) then
    execute 'update public.perfis set pin_hash = extensions.crypt(pin::text, extensions.gen_salt(''bf'')) where pin is not null and pin_hash is null';
  end if;
end
$$;

create table if not exists public.ponto_eletronico (
  id bigint generated by default as identity primary key,
  loja_id text not null,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  registrado_por uuid not null references auth.users(id) on delete restrict,
  tipo text not null check (tipo in ('entrada', 'saida')),
  latitude numeric check (latitude between -90 and 90),
  longitude numeric check (longitude between -180 and 180),
  criado_em timestamptz not null default now()
);
alter table public.ponto_eletronico add column if not exists loja_id text;
alter table public.ponto_eletronico add column if not exists registrado_por uuid references auth.users(id) on delete restrict;
alter table public.ponto_eletronico add column if not exists criado_em timestamptz not null default now();
update public.ponto_eletronico ponto
set loja_id = perfil.loja_id
from public.perfis perfil
where ponto.loja_id is null and ponto.usuario_id = perfil.id;
update public.ponto_eletronico
set registrado_por = usuario_id
where registrado_por is null;
create index if not exists ponto_eletronico_loja_criado_idx
  on public.ponto_eletronico (loja_id, criado_em desc);
create index if not exists ponto_eletronico_usuario_criado_idx
  on public.ponto_eletronico (usuario_id, criado_em desc);

alter table public.ponto_eletronico enable row level security;
revoke all on public.ponto_eletronico from public, anon, authenticated;
grant select on public.ponto_eletronico to authenticated;
do $$
begin
  if to_regclass('public.ponto_eletronico_id_seq') is not null then
    grant usage, select on sequence public.ponto_eletronico_id_seq to authenticated;
  end if;
end
$$;

drop policy if exists "gestao consulta ponto da loja" on public.ponto_eletronico;
create policy "gestao consulta ponto da loja"
on public.ponto_eletronico for select to authenticated
using (
  loja_id = (select private.loja_atual())
  and (select private.papel_atual()) in ('owner', 'gerente')
);
drop policy if exists "assinatura ativa da loja" on public.ponto_eletronico;
create policy "assinatura ativa da loja"
on public.ponto_eletronico as restrictive for select to authenticated
using (
  loja_id = (select private.loja_atual())
  and (select private.assinatura_atual_ativa())
);

create or replace function public.registrar_ponto(
  p_funcionario_id uuid,
  p_pin text,
  p_tipo text,
  p_latitude numeric,
  p_longitude numeric
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario uuid := auth.uid();
  v_loja text;
  v_papel text;
  v_pin_hash text;
begin
  select loja_id, role into v_loja, v_papel
  from public.perfis where id = v_usuario and status = 'ativo';
  if v_loja is null or v_papel not in ('owner', 'gerente') then
    raise exception 'Usuário sem permissão para registrar ponto';
  end if;
  if not (select private.assinatura_atual_ativa()) then
    raise exception 'Assinatura da loja indisponível';
  end if;
  if p_tipo not in ('entrada', 'saida') then
    raise exception 'Tipo de ponto inválido';
  end if;
  if p_latitude not between -90 and 90 or p_longitude not between -180 and 180 then
    raise exception 'Localização inválida';
  end if;

  select pin_hash into v_pin_hash
  from public.perfis
  where id = p_funcionario_id and loja_id = v_loja and status = 'ativo';
  if v_pin_hash is null or extensions.crypt(p_pin, v_pin_hash) <> v_pin_hash then
    raise exception 'PIN incorreto';
  end if;

  insert into public.ponto_eletronico (
    loja_id, usuario_id, registrado_por, tipo, latitude, longitude
  ) values (
    v_loja, p_funcionario_id, v_usuario, p_tipo, p_latitude, p_longitude
  );
  return jsonb_build_object('ok', true, 'tipo', p_tipo);
end;
$$;
revoke all on function public.registrar_ponto(uuid, text, text, numeric, numeric) from public, anon;
grant execute on function public.registrar_ponto(uuid, text, text, numeric, numeric) to authenticated;

create or replace function public.definir_pin_ponto(
  p_funcionario_id uuid,
  p_novo_pin text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_usuario uuid := auth.uid();
  v_loja text;
  v_papel text;
begin
  select loja_id, role into v_loja, v_papel
  from public.perfis where id = v_usuario and status = 'ativo';
  if v_loja is null or v_papel not in ('owner', 'gerente') then
    raise exception 'Usuário sem permissão para definir PIN';
  end if;
  if not (select private.assinatura_atual_ativa()) then
    raise exception 'Assinatura da loja indisponível';
  end if;
  if p_novo_pin !~ '^[0-9]{4,8}$' then
    raise exception 'O PIN deve conter entre 4 e 8 números';
  end if;

  update public.perfis
  set pin_hash = extensions.crypt(p_novo_pin, extensions.gen_salt('bf')),
      updated_at = now()
  where id = p_funcionario_id and loja_id = v_loja and status = 'ativo';
  if not found then
    raise exception 'Colaborador não encontrado';
  end if;

  insert into public.auditoria_operacional (
    loja_id, usuario_id, acao, entidade, entidade_id, payload
  ) values (v_loja, v_usuario, 'alterou_pin', 'perfil', p_funcionario_id::text, '{}'::jsonb);
end;
$$;
revoke all on function public.definir_pin_ponto(uuid, text) from public, anon;
grant execute on function public.definir_pin_ponto(uuid, text) to authenticated;

-- Reduz a exposição do perfil: PIN e seu hash nunca são retornados pela API.
revoke select on public.perfis from authenticated;
grant select (id, email, nome, role, status, loja_id, updated_at) on public.perfis to authenticated;

commit;
