begin;

-- Metadados comerciais e de CRM usados pelo aplicativo.
alter table public.produtos add column if not exists quantidade_minima_compra numeric not null default 1 check (quantidade_minima_compra > 0);
alter table public.produtos add column if not exists multiplo_compra numeric not null default 1 check (multiplo_compra > 0);
alter table public.clientes add column if not exists email text;
alter table public.clientes add column if not exists tags text[] not null default '{}';
alter table public.clientes add column if not exists observacoes text;
alter table public.movimentacoes add column if not exists motivo text check (motivo is null or motivo in ('compra','venda','inventario','perda','quebra','validade','devolucao','outro'));
alter table public.movimentacoes add column if not exists aprovado_por uuid references auth.users(id);
alter table public.movimentacoes add column if not exists aprovado_em timestamptz;

create index if not exists produtos_loja_barcode_idx on public.produtos(loja_id, barcode) where barcode is not null;
create index if not exists movimentacoes_loja_validade_idx on public.movimentacoes(loja_id, validade) where validade is not null;
create index if not exists clientes_loja_telefone_idx on public.clientes(loja_id, telefone) where telefone is not null;
create index if not exists vendas_loja_criado_idx on public.vendas(loja_id, criado_em desc);

create table if not exists public.historico_precos_compra (
  id bigint generated by default as identity primary key,
  loja_id text not null,
  produto_id text not null references public.produtos(id) on delete cascade,
  pedido_id uuid references public.pedidos_compra(id) on delete set null,
  fornecedor text,
  preco_unitario numeric(12,2) not null check (preco_unitario >= 0),
  registrado_em timestamptz not null default now()
);
create index if not exists historico_precos_loja_produto_idx on public.historico_precos_compra(loja_id, produto_id, registrado_em desc);
alter table public.historico_precos_compra enable row level security;
revoke all on public.historico_precos_compra from anon;
grant select, insert on public.historico_precos_compra to authenticated;
grant usage, select on sequence public.historico_precos_compra_id_seq to authenticated;

create table if not exists public.inventarios (
  id text primary key,
  loja_id text not null,
  criado_por uuid not null references auth.users(id),
  aprovado_por uuid references auth.users(id),
  status text not null default 'aberto' check (status in ('aberto','aguardando_aprovacao','aprovado','cancelado')),
  observacao text,
  criado_em timestamptz not null default now(),
  aprovado_em timestamptz
);
create table if not exists public.itens_inventario (
  inventario_id text not null references public.inventarios(id) on delete cascade,
  produto_id text not null references public.produtos(id),
  estoque_sistema numeric not null,
  estoque_contado numeric not null check (estoque_contado >= 0),
  primary key (inventario_id, produto_id)
);
alter table public.inventarios enable row level security;
alter table public.itens_inventario enable row level security;
revoke all on public.inventarios, public.itens_inventario from anon;
grant select, insert, update on public.inventarios, public.itens_inventario to authenticated;

-- Helpers não expostos evitam políticas recursivas em perfis.
create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create or replace function private.loja_atual() returns text
language sql stable security definer set search_path = ''
as $$ select loja_id from public.perfis where id = (select auth.uid()) limit 1 $$;
create or replace function private.papel_atual() returns text
language sql stable security definer set search_path = ''
as $$ select role from public.perfis where id = (select auth.uid()) limit 1 $$;
revoke all on function private.loja_atual(), private.papel_atual() from public, anon;
grant execute on function private.loja_atual(), private.papel_atual() to authenticated;

drop policy if exists "ler historico precos da loja" on public.historico_precos_compra;
create policy "ler historico precos da loja" on public.historico_precos_compra for select to authenticated
using (loja_id = (select private.loja_atual()) and (select private.papel_atual()) in ('owner','gerente'));
drop policy if exists "registrar preco da loja" on public.historico_precos_compra;
create policy "registrar preco da loja" on public.historico_precos_compra for insert to authenticated
with check (loja_id = (select private.loja_atual()) and (select private.papel_atual()) in ('owner','gerente'));

drop policy if exists "inventario da gestao" on public.inventarios;
create policy "inventario da gestao" on public.inventarios for all to authenticated
using (loja_id = (select private.loja_atual()) and (select private.papel_atual()) in ('owner','gerente'))
with check (loja_id = (select private.loja_atual()) and (select private.papel_atual()) in ('owner','gerente'));
drop policy if exists "itens inventario da gestao" on public.itens_inventario;
create policy "itens inventario da gestao" on public.itens_inventario for all to authenticated
using (exists (select 1 from public.inventarios i where i.id = inventario_id and i.loja_id = (select private.loja_atual())) and (select private.papel_atual()) in ('owner','gerente'))
with check (exists (select 1 from public.inventarios i where i.id = inventario_id and i.loja_id = (select private.loja_atual())) and (select private.papel_atual()) in ('owner','gerente'));

-- Corrige a origem clássica de recursão infinita na tabela perfis.
alter table public.perfis enable row level security;
do $$ declare p record; begin
  for p in select policyname from pg_policies where schemaname = 'public' and tablename = 'perfis'
  loop execute format('drop policy if exists %I on public.perfis', p.policyname); end loop;
end $$;
create policy "ler proprio perfil" on public.perfis for select to authenticated using (id = (select auth.uid()));
create policy "gestao le equipe" on public.perfis for select to authenticated
using (loja_id = (select private.loja_atual()) and (select private.papel_atual()) in ('owner','gerente'));
create policy "gestao cria equipe" on public.perfis for insert to authenticated
with check (loja_id = (select private.loja_atual()) and (select private.papel_atual()) = 'owner');
create policy "gestao atualiza equipe" on public.perfis for update to authenticated
using (loja_id = (select private.loja_atual()) and (select private.papel_atual()) = 'owner')
with check (loja_id = (select private.loja_atual()) and role in ('owner','gerente','atendente','entregador'));
create policy "gestao remove equipe" on public.perfis for delete to authenticated
using (loja_id = (select private.loja_atual()) and (select private.papel_atual()) = 'owner' and id <> (select auth.uid()));

commit;
